### ISSUE TITLE
Metric time... why 12 months?

### ISSUE THREAD

**Issue by mindey** [lakhanmankani/metric-time#4]
> "The French Republic calendar calendar consists of 12 months, each with exactly 30 days."

If we want a decimal (base-10) time that makes sense, why 12 months?

> Years are counted in relation to the year 1792.

Seems quite arbitrary starting date, what does it signify? I think, it is best to choose a geological moment, like the Big Bang... or something more significant than a religious figure 2K years ago. What could this be? I think, the beginning of birth of silicon-based life out of carbon-based life, in the 20-th century (e.g., Unix-time starting point) could be that date.

So, I've also created a variant of decimal time, feel free to look at *[detime](https://github.com/mindey/detime)*.

**Comment by lakhanmankani** [comment]
Interesting work! Since this is not an issue I'm closing this.
